CREATE TABLE `platform`.`shop` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `shop_name` VARCHAR(50) NOT NULL,
  `shop_avatar` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `tagline` VARCHAR(50) NULL,
  `category` VARCHAR(50) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `shop_name_UNIQUE` (`shop_name` ASC) VISIBLE,
  INDEX `category_INDEX` (`category` ASC) VISIBLE,
  CONSTRAINT `user_id_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `platform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
