CREATE TABLE `platform`.`shop` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `shop_name` VARCHAR(50) NOT NULL,
  `shop_banner` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `current_occupation` VARCHAR(255) NULL,
  `skills` JSON NULL,
  `personal_website` VARCHAR(255) NULL,
  `instagram_url` VARCHAR(255) NULL,
  `category` VARCHAR(50) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `shop_name_UNIQUE` (`shop_name` ASC) VISIBLE);
