CREATE TABLE `platform`.`inspiration` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `shop_id` BIGINT(20) UNSIGNED NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `tags` JSON NOT NULL,
  `category` JSON NOT NULL,
  `description` LONGTEXT NOT NULL,
  `image_url` JSON NOT NULL,
  `catalog_id` BIGINT(20) UNSIGNED NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
  PRIMARY KEY (`id`),
  INDEX `index_shop_id` (`shop_id` ASC) VISIBLE)
ENGINE = InnoDB;
