CREATE TABLE `platform`.`order_chat` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_no` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL, 
  PRIMARY KEY (`id`),
  UNIQUE INDEX `invoice_no_UNIQUE` (`invoice_no` ASC) VISIBLE);


CREATE TABLE `platform`.`order_chat_history` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_chat_id` BIGINT(20) UNSIGNED NOT NULL,
  `content` LONGTEXT NOT NULL,
  `origin` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));
